name: Run static checks and unit tests

# Any change in triggers needs to be reflected in the concurrency group.
on:
  push:
    branches:
      - master
      - v*
  pull_request:
    branches:
    - master
    - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
    - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
      with:
        go-version: '1.20.3'
    - name: Run static checks
      uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc
      with:
        version: v1.52.2
        args: --config=.golangci.yml --verbose
        skip-cache: true
    - name: Check module vendoring
      run: |
        go mod tidy
        go mod vendor
        go mod verify
        git status
        test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy && go mod vendor', and submit your changes"; exit 1)
    - name: Run unit tests
      run: make test
    - name: Build
      run: make
    - name: Build release binaries
      run: make release
